version: '3'
services:
  python3:
    restart: always
    build: ./infra/python/
    container_name: 'vocabulary-app'
    working_dir: '/root/'
    tty: true
    volumes: 
      - ./backend/:/root
      - ./infra/vim/.vimrc:/root/.vimrc